table SysHttpRequestLog
	lineageTag: 4d561a0b-688f-4004-9dc5-6c9b6b101d80

	column Name
		dataType: string
		lineageTag: 69517844-2201-4fd4-8b9e-cb16fdf58e62
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Group
		dataType: string
		lineageTag: e6f776c9-bb62-41c4-9692-29b200106d87
		summarizeBy: none
		sourceColumn: Group

		annotation SummarizationSetBy = Automatic

	column RequstNo
		dataType: int64
		formatString: 0
		lineageTag: ebe8ae10-505a-42bd-aa92-2c49e94225fe
		summarizeBy: sum
		sourceColumn: RequstNo

		annotation SummarizationSetBy = Automatic

	column RequestContent
		dataType: string
		lineageTag: 6ad6b0eb-3566-46d2-99b6-4c6df75ab135
		summarizeBy: none
		sourceColumn: RequestContent

		annotation SummarizationSetBy = Automatic

	column RequestBody
		dataType: string
		lineageTag: e3ab10b5-ffc6-42b1-92b6-76e8dd4129c1
		summarizeBy: none
		sourceColumn: RequestBody

		annotation SummarizationSetBy = Automatic

	column AttemptNo
		dataType: int64
		formatString: 0
		lineageTag: e4b6a847-3d2d-4650-ba04-aac8228872de
		summarizeBy: sum
		sourceColumn: AttemptNo

		annotation SummarizationSetBy = Automatic

	column RequestResponseTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 352d889d-ba05-4dc2-ae95-40b013368362
		summarizeBy: none
		sourceColumn: RequestResponseTime

		variation Variation
			isDefault
			relationship: 6b02e262-b775-45e1-83f8-6da491659f6a
			defaultHierarchy: LocalDateTable_26364b3b-064a-4b2a-9b1c-2becf789b738.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column RequestDelay
		dataType: double
		lineageTag: b64664cc-126c-4702-b2f3-558502efcf19
		summarizeBy: sum
		sourceColumn: RequestDelay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HasConnectionError
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c0faa866-4516-4604-88da-24ca24c8c8f1
		summarizeBy: none
		sourceColumn: HasConnectionError

		annotation SummarizationSetBy = Automatic

	column ConnectionErrorReason
		dataType: string
		lineageTag: f53d9468-a278-4143-988e-4a3af1659385
		summarizeBy: none
		sourceColumn: ConnectionErrorReason

		annotation SummarizationSetBy = Automatic

	column ConnectionErrorMessage
		dataType: string
		lineageTag: 4fbe3179-df74-44a8-84e3-23bdb7bab5cb
		summarizeBy: none
		sourceColumn: ConnectionErrorMessage

		annotation SummarizationSetBy = Automatic

	column ConnectionErrorDetails
		dataType: string
		lineageTag: 3c9c57c4-85c7-4fef-b2be-6ff3d44c310d
		summarizeBy: none
		sourceColumn: ConnectionErrorDetails

		annotation SummarizationSetBy = Automatic

	column HttpResponseStatus
		dataType: int64
		formatString: 0
		lineageTag: 8ea9beb4-05e2-4c53-bb4e-53b8866f9980
		summarizeBy: sum
		sourceColumn: HttpResponseStatus

		annotation SummarizationSetBy = Automatic

	column ResponseErrorCode
		dataType: string
		lineageTag: 610a0fad-0f8c-407f-9ff1-bd69689aaffd
		summarizeBy: none
		sourceColumn: ResponseErrorCode

		annotation SummarizationSetBy = Automatic

	column ResponseErrorMessage
		dataType: string
		lineageTag: 62f8ef67-8a6b-4a44-acf0-5f53678bd980
		summarizeBy: none
		sourceColumn: ResponseErrorMessage

		annotation SummarizationSetBy = Automatic

	column IsEmpty
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 58c90183-eace-4fe7-8388-9f193195cdff
		summarizeBy: none
		sourceColumn: IsEmpty

		annotation SummarizationSetBy = Automatic

	partition SysHttpRequestLog = m
		mode: import
		queryGroup: Logging
		source = ```
				let
				    Source = SysHttpRequestData,
				
				    CheckEmptiness = Table.AddColumn(SysHttpRequestData, "IsEmpty", each 
				                                                                            (try Record.FieldCount([Data]) = 0 otherwise true) 
				                                                                        and (try List.IsEmpty([Data][value]) otherwise true) 
				                                                                        and (try List.IsEmpty([Data][Cells]) otherwise true), 
				                                                                        type logical
				                                    ),
				    ExpendResponseRecord = Table.ExpandRecordColumn(CheckEmptiness, "Data", {"@metadata", "error"}),
				    ExpandMetadataTable = Table.ExpandTableColumn(ExpendResponseRecord, "@metadata", {
				                                                                                        "RequstNo"
				                                                                                        , "RequestContent"
				                                                                                        , "RequestBody"
				                                                                                        , "AttemptNo"
				                                                                                        , "RequestResponseTime"
				                                                                                        , "RequestDelay"
				                                                                                        , "HasConnectionError"
				                                                                                        , "ConnectionErrorReason"
				                                                                                        , "ConnectionErrorMessage"
				                                                                                        , "ConnectionErrorDetails"
				                                                                                        , "HttpResponseStatus"
				                                                                                    }
				                                                ),
				    ExpendErrorRecord = Table.ExpandRecordColumn(ExpandMetadataTable, "error", {"code", "message"}, {"ResponseErrorCode", "ResponseErrorMessage"}),
				    TransformColumnTypes = Table.TransformColumnTypes(ExpendErrorRecord, {
				                                                                            {"RequstNo", Int64.Type}
				                                                                            , {"AttemptNo", Int64.Type}
				                                                                            , {"RequestResponseTime", type datetime}
				                                                                            , {"RequestDelay", type number}
				                                                                            , {"HasConnectionError", type logical}
				                                                                            , {"HttpResponseStatus", Int64.Type}	
				    })
				in
				    TransformColumnTypes
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

